spring:
  application:
    name: search-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/htsat-search?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      maxActive: -1
      maxWait: -1
      maxIdle: 100
      minIdle: 0
    timeout: 0
  data:
    solr:
      host: http://localhost:8983/solr/mycore

server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.htsat.search.model

#logging:
#  file: search.log



#spring.data.solr.host=http://192.168.1.44:8983/solr/e-commerce
#spring.data.solr.host=http://localhost:8983/solr/mycore